USE CODER_OBJETOS_BBDD ;

CREATE VIEW Vista_Clientes_Con_Deudas AS
	SELECT c.*, COUNT(d.ID_DEUDA) AS Cantidad_Deudas
	FROM CLIENTES c
	LEFT JOIN DEUDAS d ON c.NRO_CLIENTE = d.NRO_CLIENTE
	GROUP BY c.NRO_CLIENTE;


CREATE VIEW Vista_Ventas_Detallada AS
SELECT v.NRO_FACTURA, v.FECHA, v.MEDIO_DE_PAGO, v.PRECIO_FINAL,
       c.NOMBRE AS Cliente, vd.NOMBRE AS Vendedor, p.NOMBRE AS Producto
	FROM VENTAS v
	JOIN CLIENTES c ON v.NRO_CLIENTE = c.NRO_CLIENTE
	JOIN VENDEDORES vd ON v.VENDEDOR = vd.NRO_VENDEDOR
	JOIN PRODUCTOS p ON v.CODIGO_PRODUCTO = p.CODIGO;


CREATE VIEW Vista_Deudas_Pendientes AS
	SELECT d.ID_DEUDA, c.NOMBRE AS Cliente, d.PRODUCTOS, d.SALDO_FINAL
	FROM DEUDAS d
	JOIN CLIENTES c ON d.NRO_CLIENTE = c.NRO_CLIENTE
	WHERE d.SALDO_FINAL > 0;


CREATE VIEW Vista_Ventas_Mensuales AS
	SELECT YEAR(v.FECHA) AS Anio, MONTH(v.FECHA) AS Mes, SUM(v.PRECIO_FINAL) AS Total_Ventas
	FROM VENTAS v
	GROUP BY YEAR(v.FECHA), MONTH(v.FECHA)
	ORDER BY Anio, Mes;


CREATE VIEW Vista_Proveedores_Con_Descuentos AS
	SELECT p.*, CONCAT('Descuento del ', p.DESCUENTOS, '%') AS Detalle_Descuento
	FROM PROVEEDORES p;

CREATE VIEW Ventas_por_productos AS
    SELECT V.*, P.NOMBRE AS NOMBRE_PRODUCTO, P.PRECIO AS PRECIO_PRODUCTO
    FROM VENTAS V
    JOIN PRODUCTOS P ON V.CODIGO_PRODUCTO = P.CODIGO;

SELECT * FROM Vista_Clientes_Con_Deudas;
SELECT * FROM Vista_Ventas_Detallada;
SELECT * FROM Vista_Deudas_Pendientes;
SELECT * FROM Vista_Ventas_Mensuales;
SELECT * FROM Vista_Proveedores_Con_Descuentos;
SELECT * FROM Ventas_por_productos;
